name: Docs

on:
    push:
        branches: [main]

env:
    FORCE_COLOR: 1 #output ANSI color code
permissions: {}

jobs:
    docs:
        permissions:
            contents: write # to push pages branch (peaceiris/actions-gh-pages)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Install uv
              uses: astral-sh/setup-uv@v8.2.0

            - name: Install Python
              run: uv python install 3.11

            - name: Install tox
              run: uv tool install tox --with tox-uv

            - name: Build documentation
              run: tox -e docs

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs/_build/html
                publish_branch: gh-pages
                force_orphan: true # every deployment should wipe the branch history(gh-pages) and creates a new commit with the new content.

